### PR TITLE
delete reference to InvalidAction

### PR DESCRIPTION
**Pull request by tkelman**
this appears nowhere else in the repo and is causing an UndefVarError on Travis

### CODE REVIEW

**Comment by samoconnor** [comment]
InvalidAction is dynamically created.
Fixed here: https://github.com/samoconnor/AWSCore.jl/commit/f946d890842b4bff1bff60ef5a79eba11a0f624b

```julia
julia> Pkg.test("AWSCore")
INFO: Testing AWSCore
Authenticated as: arn:aws:iam::551613799374:user/sam
Testing exceptions...
InvalidAction -- Could not find operation GetFoo for version 2010-05-08
HTTP 400 -- POST https://iam.amazonaws.com/ -- {"Error":{"Code":"InvalidAction","Message":"Could not find operation GetFoo for version 2010-05-08","Type":"Sender"},"RequestId":"b95cc740-7ca6-11e7-a9c6-c5f5feb53dc4"}


NoSuchEntity -- The user with name notauser cannot be found.
HTTP 404 -- POST https://iam.amazonaws.com/ -- {"Error":{"Code":"NoSuchEntity","Message":"The user with name notauser cannot be found.","Type":"Sender"},"RequestId":"bb5b08bc-7ca6-11e7-ae1f-011f6bf38c43"}


ValidationError -- The specified value for userName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
HTTP 400 -- POST https://iam.amazonaws.com/ -- {"Error":{"Code":"ValidationError","Message":"The specified value for userName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-","Type":"Sender"},"RequestId":"bdb1f113-7ca6-11e7-b670-cbd2962da609"}


EntityAlreadyExists -- User with name root already exists.
HTTP 409 -- POST https://iam.amazonaws.com/ -- {"Error":{"Code":"EntityAlreadyExists","Message":"User with name root already exists.","Type":"Sender"},"RequestId":"c081d924-7ca6-11e7-8e78-f90020380ba4"}


User ARN ok.
XML parsing ok.
AWS4 Signature ok.
ARNs ok.
Endpoints ok.
INFO: AWSCore tests passed
```

**Comment by tkelman** [comment]
Good enough, was wondering what the travis failure was about.

**Comment by samoconnor** [comment]
I'm afraid I've been ignoring travis because of the dependancies between my packages often nothing works on travis until everything is tagged and accepted into METADATA.

**Comment by tkelman** [comment]
Yeah it's tricky with a big set of inter-dependent packages. Users will generally be on releases so it's useful to test against release versions of dependencies, but if they're all going to be tagged together in concert then right before a set of releases it's worth testing against master of the dependencies since that's about to be the next release. You could Pkg.init on Travis to a specific branch of your fork of METADATA, but that gets to be a bit to maintain.

**Pull request closed without merging**
